config/routes.rb
Rails.application.routes.draw do

  resources :weights, only: [:index, :edit, :create, :update, :destroy]

  resources :posts do
   resources :post_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
   collection do
      get 'search'
    end
  end

  resource :users, only: [:edit,:update] do
    collection do
      get :my_page, to: 'users#show'
      patch :my_page, to: 'users#show'
      get :quit
      patch :out,to: "users#out"
      get :new ,to: "users#new"
    end
  end

  resources :diaries

  devise_for :users

  root to: 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_many :diary_images, dependent: :destroy
  attachment :image

  validates :start_time, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/diary_image.rb
class DiaryImage < ApplicationRecord
 belongs_to :diary
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
   self.favorites.exists?(user_id: user.id)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diarys, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :weights, dependent: :destroy

  validates :date, presence: true
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :weight, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    diaries_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:date])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def index
    @diaries = current_user.diarys
    @diary = Diary.new
  end

  def show
    @diaries = current_user.diarys.where(start_time: params[:date].to_date.all_day)
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id
    if @diary.save
      redirect_to diaries_path
    else
      @diaries = current_user.diarys
      render :index
    end
  end

  def show
    @diaries = current_user.diarys.where(start_time: params[:id].to_date.all_day)
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    diary = Diary.find(params[:id])
    diary.update(diary_params)
    redirect_to diaries_path
  end

  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
    redirect_to diaries_path
  end

  private

  def diary_params
    params.require(:diary).permit(:user_id, :image, :title, :body, :start_time)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: @post.id, user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
  
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_q, only: [:index, :search]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @post = Post.new
    @posts = Post.page(params[:page]).page(params[:page]).per(7).reverse_order
  end

  def show
    @post_comment = PostComment.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      @posts = Post.page(params[:page]).page(params[:page]).per(7).reverse_order
      @q = Post.ransack(params[:q])
      render :index
    end
  end

  def update
    @post.update(post_params)
    redirect_to posts_path

  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Post.ransack(params[:q])
  end
  
  def find_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:user_id,:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
   user = User.new(user_params)
   user.user_id = current_user.id
   user.save
   redirect_to my_page_users_path(current_user)
  end

  def show
   @user = current_user
   @week =  40 - (( @user.date.to_date - Date.today) / 7).to_f
   @week_day = ((@week - @week.to_i)*7).round
   @day = @user.date.to_date - Date.today
   if @day >= 0
    @day
   else
    @day = 0
   end
  end

  def edit
   @user = current_user
  end

  def update
   @user = current_user
   @user.update(user_params)
   redirect_to my_page_users_path(current_user)
  end

  def quit
  end

  def out
   @user = current_user
   @user.update(is_valid: false)
   reset_session
   redirect_to root_path
  end

end

private


def user_params
    params.require(:user).permit(:name, :email, :date)
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController

  before_action :date_check, only: :create

  def index
    @weight = Weight.new
    @weights = current_user.weights.page(params[:page]).per(7).order(date: "desc")
    @chart = []
    @weights.each do |weight|
      @chart.push([weight.date.to_datetime.strftime('%d日'), weight.weight])
    end
    @chart = @chart.reverse
  end

  def edit
    @weight = Weight.find(params[:id])
  end

  def create
    @weight = Weight.new(weight_params)
    @weight.user_id = current_user.id
    if @weight.save
      redirect_to weights_path
    else
      @weights = current_user.weights.page(params[:page]).per(7).order(date: "desc")
      @chart = []
      @weights.each do |weight|
       @chart.push([weight.date.to_datetime.strftime('%d日'), weight.weight])
      end
      render :index
    end
  end

  def update
    weight = Weight.find(params[:id])
    weight.update(weight_params)
    redirect_to weights_path
  end

  def destroy
    weight = Weight.find(params[:id])
    weight.destroy
    redirect_to weights_path
  end

  private

  def weight_params
    params.require(:weight).permit(:user_id, :weight, :date)
  end

  def date_check
    duplication_date = current_user.weights.where(date: params[:weight][:date])
    duplication_date.delete_all if duplication_date.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/diaries/edit.html.erb
<h2 class="hading offset-3 col-6">日記編集</h4>
<%= form_with model: @diary, local:true do |f| %>
  <div class="diary-editform">
    <p class="left"><%= f.attachment_field :image,class: "diaryeform" %></p>
    <%= f.text_field :title,class: "diaryform" %>
    <%= f.text_area :body,class: "diaryform" %>
    <%= f.submit '変更を保存', class: "edit-diaryform-btn" %>
</div>
<% end %>

app/views/diaries/index.html.erb
<% if @diary.errors.any? %>
  <%= @diary.errors.count %>件のエラーが発生しました
  <% @diary.errors.full_messages.each do |message| %>
    <div class="message"><%= message %></div>
  <% end %>
<% end %>
<div class="contact-form">
  <div>
  <%= form_with model: @diary, local:true do |f| %>
    <h4 class="hading">new diary</h4> <br/>
    <%= f.date_field :start_time,class: "diaryform" %>
    <%= f.text_field :title, placeholder: "タイトル",class: "diaryform" %>
    <%= f.attachment_field :image, class: "diaryform" %>
    <%= f.text_area :body, placeholder: "内容", class: "diaryform textarea" %>
    <%= f.submit '投稿', class: "diaryform-btn semibold" %>
    <% end %>
  </div>
  <div class="col-9">
  <%= month_calendar events: @diaries do |date, diary| %>
    <%= date.day %>
    <% if diary.count > 0 %>
      <%= link_to diary_path(date.year.to_s + "-" + date.month.to_s + "-" + date.day.to_s) do %>
        <% diary. each do |d|%>
         <%= d.title %><br/>
        <% end %>
      <% end %>
    <%end%>
  <% end %>
  </div>
</div>

app/views/diaries/show.html.erb
<h4 class="hading col-3">todays,diary</h4>
<div class="row">
  <% @diaries.each do |diary| %>
  <div class="col-md-4">
    <section class="card">
      <div class="card-img-top">
        <%= attachment_image_tag diary, :image, fallback: "noimage-760x460", class: "img-fluid post-img"%>
      </div>
      <div class="card-content">
        <h1 class="card-title"><%= diary.title %></h1>
        <p class="card-text"><%= diary.body %></p>
      </div>
      <div class="card-link">
        <%= link_to "投稿編集", edit_diary_path(diary.id),class:"fas fa-edit" %>
        <%= link_to "投稿削除", diary_path(diary.id), method: :delete, class: 'fas fa-trash-alt', data: { confirm: "【確認】投稿を削除してもよろしいですか？" } %>
      </div>
    </section>
  </div>
  <% end %>
</div>

app/views/favorites/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
  <p>
    <%= link_to post_favorites_path(post), method: :delete, remote: true do %>️
      いいね<%= post.favorites.count %>💖
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to post_favorites_path(post), method: :post, remote: true do %>️
      いいね<%= post.favorites.count %>🤍
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_area_<%= @post.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$("#favorite_area_<%= @post.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/posts/edit.html.erb
<h2 class="hading offset-3 col-6">投稿編集</h4>
<%= form_with model: @post, local:true do |f| %>
  <p class="editform">
    <%= f.text_field :title,class: "postform" %>
    <%= f.text_area :body,class: "postform" %>
    <%= f.submit "変更",class:"postform-btn" %>
  </p>
<% end %>

app/views/posts/index.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <% @post.errors.full_messages.each do |message| %>
    <div class="message"><%= message %></div>
  <% end %>
<% end %>
<div class="contact-form">
  <div class="col-3">
  <%= form_with model: @post, local:true do |f| %>
    <h4 class="hading">new post</h4> <br/>
    <div>
      <%= f.text_field :title, placeholder: "タイトル",class: "postform" %>
    </div>
    <div>
      <%= f.text_area :body, placeholder: "内容",class: "postform" %>
    </div>
    <div class="center-btn">
      <%= f.submit '投稿', class: "postform-btn" %>
    </div>
  <% end %>
  </div>
  <div class="col-9">
    <div class="search"><br/>
      <%= search_form_for @q, url: search_posts_path do |f| %>
        <%= f.search_field :title_cont, placeholder: "タイトル検索" %>
        <%= f.button :type => "submit" do %>
          <i class='fa fa-search'></i>
        <% end %>
      <% end %>
    </div>
    <div class="offset-2"><%= paginate @posts %></div>
    <table class="offset-1 main-not">
      <thead class="table table-bordered">
        <tr class="table-danger">
          <th>投稿日</th>
          <th width="13%">名前</th>
          <th width="17%">タイトル</th>
          <th width="40%">内容</th>
          <th width="14%">いいね</th>
          <th width="15%">コメント</th>
        </tr>
      </thead>
      <% @posts. each do |post|%>
      <tbody class="table table-bordered">
        <tr>
          <td><%= post.user.created_at.strftime('%Y/%m/%d') %> </td>
          <td><%= post.user.name %></td>
          <td><%= post.title %></td>
          <td>
            <%= post.body.truncate(30) %><br/>
            <% if post.user == current_user %>
              <%= link_to "編集", edit_post_path(post),class: "fas fa-edit" %>
              <%= link_to "削除", post_path(post), method: :delete,class: "fas fa-trash-alt", data: { confirm: "【確認】投稿を削除してもよろしいですか？" } %>
            <% end %>
          </td>
          <td id="favorite_area_<%= post.id %>">
            <%= render 'favorites/favorite',post: post %>
           </td>
          <td><%= link_to "コメント#{post.post_comments.count} ", post_path(post.id) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/posts/search.html.erb
<table class="table table-bordered">
  <thead>
    <tr class="table-danger">
      <th>投稿日</th>
      <th width="13%">名前</th>
      <th width="17%">タイトル</th>
      <th width="40%">内容</th>
      <th width="15%">いいね</th>
      <th width="15%">コメント</th>
    </tr>
  </thead>
  <% @results.each do |post| %>
  <tbody>
    <tr>
      <td><%= post.user.updated_at.strftime('%Y/%m/%d') %></td>
      <td><%= post.user.name %></td>
      <td><%= post.title %></td>
      <td>
        <%= post.body %><br/>
        <% if post.user == current_user %>
          <%= link_to "編集", edit_post_path(post),class: "fas fa-edit" %>
          <%= link_to "削除", post_path(post), method: :delete,class: "fas fa-trash-alt", data: { confirm: "【確認】投稿を削除してもよろしいですか？" } %>
        <% end %>
      </td>
      <td id="favorite_area_<%= post.id %>">
        <%= render 'favorites/favorite',post: post %>
       </td>
      <td><%= link_to "コメント#{post.post_comments.count} ", post_path(post.id) %></td>
    </tr>
  </tbody>
  <% end %>
</table>
<%= link_to '戻る', posts_path %>

app/views/posts/show.html.erb
<% if @post_comment.errors.any? %>
  <%= @post_comment.errors.count %>件のエラーが発生しました
  <% @post_comment.errors.full_messages.each do |message| %>
    <div class="message"><%= message %></div>
  <% end %>
<% end %>
<div class="contact-form">
  <div class="col-3">
    <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
    <h4 class="hading">new comment</h4><br/>
    <div>
      <%= f.text_area :comment, rows:'3',placeholder: "コメントをここに",class: "postform" %>
    </div>
    <div>
      <%= f.submit '投稿', class: "postform-btn" %>
    </div>
    <% end %>
  </div>
  <div class="post-week offset-2 col-5">
    <div class=" post-content">
      <h2>投稿内容</h2>
      <div class="card-body">
        <h4 class="card-title"><%= @post.title %></h4>
        <p class="card-text"><%= @post.body %></p>
        <p class="card-right"><%= @post.created_at.strftime('%Y/%m/%d') %></p>
        <p class="card-right"><%= @post.user.name %></p>
      </div>
    </div>
  </div>
</div>

<div class="offset-3">
  <h4 class="mt-5">コメント一覧</h4>
  <p>コメント件数：<%= @post.post_comments.count %></p>
  <table id="id">
    <thead class="table table-bordered">
      <tr class="table-danger">
        <th width="13%">コメント日</th>
        <th width="17%">コメント者</th>
        <th width="40%">コメント内容</th>
        <th width="15%">編集</th>
      </tr>
    </thead>
    <tbody class="table table-bordered">
    <% @post.post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
        <td><%= post_comment.user.name %></td>
        <td><%= post_comment.comment %></td>
        <td>
          <% if post_comment.user == current_user %>
            <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class="form-wrapper">
	<h2>会員情報編集</h2>
	<%= form_with model: @user, url: users_path, local:true do |f| %>
	<table height="400" style="font-size : 20px;" >
    <tr>
      <td width="30%">氏名</td>
      <td width="40%"><%= f.text_field :name,class:"form" %></td>
      <td width="30%"></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= f.email_field :email,class:"form" %></td>
      <td></td>
    </tr>
    <tr>
      <td>出産予定日</td>
      <td><%= f.date_field :date,class:"form" %></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit '編集内容を保存',class:"btn btn-success" %></td>
      <td><%= link_to " 退会する", quit_users_path, class: "btn btn-danger" %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/quit.html.erb
<div>
  <strong>本当に退会しますか？</strong>
    <div>
      退会すると会員情報登録や<br/>
      これまでの日記記録等が閲覧できなくなります。<br/><br/>
      退会する場合は,「退会する」をクリックしてください。
    </div>
    <%= link_to "退会しない", my_page_users_path, class: 'btn btn-primary' %>
    <%= link_to "退会する", out_users_path,method: :patch, class: 'btn btn-danger' %>
</div>

app/views/users/show.html.erb
<div class="contact-form">
  <div class="mypage-wrapper col-5">
  <h2><span><%= @user.name %>さんの会員情報</span></h2>
  <table height="350" style="font-size : 25px;">
   	<tr>
	    <td width="30%">会員ID</td>
      <td width="70%"><%= @user.id %></td>
	  </tr>
		<tr>
			<td>名前</td>
	    <td><%= @user.name %></td>
		</tr>
		<tr>
		  <td>メールアドレス</td>
      <td><%= @user.email %> </td>
		</tr>
		<tr>
		  <td>会員ステータス</td>
      <td>
    	  <% if @user.is_valid %>
	        <p class="text-success">有効</p>
	      <% else %>
	        <p class="text-danger">退会</p>
		    <% end %>
      </td>
		</tr>
		<tr>
      <td></td>
      <td><%= link_to "編集する", edit_users_path, class: "btn btn-success" %>
    </tr>
  </table>
  </div>
	<div class="maternity-week offset-2 col-5">
		<h6 class="week_left"><%= Date.today.strftime('%Y年%-m月%d日') %><h6>
		<h4 class="maternity-margin">予定日</h4>
		<h3 class="maternity-margin"><%= @user.date.strftime('%Y年%-m月%d日') %></h3>
		<h4 class="maternity-margin">現在の週数</h4>
		<h1 class="maternity-margin font-special"><%= @week.to_i %>週目<%= @week_day %>日</h1>
		<h6 class="maternity-margin">出産まで残り<%= @day.to_i %>日</h6>
	</div>
</div>

app/views/weights/edit.html.erb
<h2 class="hading offset-3 col-6">体重編集</h4>
<%= form_with model: @weight, local:true do |f| %>
  <p class="editform">
  <%= f.date_field :date, value: @weight.date,class: "weight-editform" %>
  <%= f.number_field :weight, step: '0.1',class: "weight-editform" %>
  <%= f.submit '変更を保存', class: "edit-weightform-btn semibold" %>
</p>
<% end %>

app/views/weights/index.html.erb
<% if @weight.errors.any? %>
  <%= @weight.errors.count %>件のエラーが発生しました
  <% @weight.errors.full_messages.each do |message| %>
    <div class="message"><%= message %></div>
  <% end %>
<% end %>
<div class="contact-form">
  <div class="col-3">
  <%= form_with model: @weight, local:true do |f| %>
    <h4 class="hading">new weight</h4><br/>
    <div>
      <%= f.date_field :date,class: "weightform" %>
    </div>
    <div>
      <%= f.number_field :weight, placeholder: "KG", step: '0.1',class: "weightform" %>
    </div>
    <div>
      <%= f.submit '投稿', class: "weightform-btn" %>
    </div>
  <% end %>
  </div>
  <div class="col-9">
    <%= line_chart @chart ,width: "auto", height: "350px", min: 40, max: 100, colors: ["#A0D6E9", "#A0D6E9"], xtitle: "DAY", ytitle: "WEIGHT", decimal: "," %>
  </div>
</div>

<div class="weight offset-3">
  <table class="table table-bordered">
    <thead>
      <tr class="table-info">
        <th width="30%">日付</th>
        <th width="30%">体重</th>
        <th width="40%">編集</th>
      </tr>
    </thead>
    <%= paginate @weights %>
    <% @weights. each do |weight|%>
    <tbody>
      <tr>
        <td><%= weight.date %></td>
        <td><%= weight.weight %>kg</td>
        <td>
          <% if weight.user == current_user %>
            <%= link_to "編集", edit_weight_path(weight),class: "fas fa-edit" %>
            <%= link_to "削除", weight_path(weight), method: :delete,class: "fas fa-trash-alt" %>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>