config/routes.rb
Rails.application.routes.draw do

  resources :weights, only: [:index, :edit, :create, :update, :destroy]

  resources :posts do
   resources :post_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
   collection do
      get 'search'
    end
  end

  resource :users, only: [:edit,:update] do
    collection do
      get :my_page, to: 'users#show'
      patch :my_page, to: 'users#show'
      get :quit
      patch :out,to: "users#out"
      get :new ,to: "users#new"
    end
  end

  resources :diaries

  devise_for :users

  root to: 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_many :diary_images, dependent: :destroy
  attachment :image

  validates :start_time, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/diary_image.rb
class DiaryImage < ApplicationRecord
 belongs_to :diary
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
   self.favorites.exists?(user_id: user.id)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diarys, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :weights, dependent: :destroy

  validates :date, presence: true
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :weight, presence: true
  validates :date, presence: true
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def index
    @diaries = current_user.diarys
    @diary = Diary.new
  end

  def show
    @diaries = current_user.diarys.where(start_time: params[:date].to_date.all_day)
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id
    if @diary.save
      redirect_to diaries_path
    else
      @diaries = current_user.diarys
      render :index
    end
  end

  def show
    @diaries = current_user.diarys.where(start_time: params[:id].to_date.all_day)
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    diary = Diary.find(params[:id])
    diary.update(diary_params)
    redirect_to diaries_path
  end

  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
    redirect_to diaries_path
  end

  private

  def diary_params
    params.require(:diary).permit(:user_id, :image, :title, :body, :start_time)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
  
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_q, only: [:index, :search]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @post = Post.new
    @posts = Post.page(params[:page]).page(params[:page]).per(7).reverse_order
  end

  def show
    @post_comment = PostComment.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      @posts = Post.page(params[:page]).page(params[:page]).per(7).reverse_order
      @q = Post.ransack(params[:q])
      render :index
    end
  end

  def update
    @post.update(post_params)
    redirect_to posts_path

  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Post.ransack(params[:q])
  end
  
  def find_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:user_id,:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
   user = User.new(user_params)
   user.user_id = current_user.id
   user.save
   redirect_to my_page_users_path(current_user)
  end

  def show
   @user = current_user
   @week =  40 - (( @user.date.to_date - Date.today) / 7).to_f
   @week_day = ((@week - @week.to_i)*7).round
   @day = @user.date.to_date - Date.today
   if @day >= 0
    @day
   else
    @day = 0
   end
  end

  def edit
   @user = current_user
  end

  def update
   @user = current_user
   @user.update(user_params)
   redirect_to my_page_users_path(current_user)
  end

  def quit
  end

  def out
   @user = current_user
   @user.update(is_valid: false)
   reset_session
   redirect_to root_path
  end

end

private


def user_params
    params.require(:user).permit(:name, :email, :date)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maternity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
            <h1><%= image_tag('logo.png', size:"100x100", class: 'blog-image') %>HAPPY MATERNITY</h1>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "MYPAGE", my_page_users_path, class: 'nav-link text-success fas fa-user-cog' %>
                </li>
                <li class="nav-item">
                  <%= link_to "DIARY", diaries_path, class: 'nav-link text-warning fas fa-book' %>
                </li>
                <li class="nav-item">
                  <%= link_to "WEIGHT", weights_path,class: 'nav-link text-info fas fa-weight' %>
                </li>
                <li class="nav-item">
                  <%= link_to "POST", posts_path, class: 'nav-link text-danger fas fa-pencil-alt' %>
                </li>
                <li class="nav-item">
                  <%= link_to "LOGOUT", destroy_user_session_path, method: :delete,class: 'nav-link text-dark fas fa-sign-out-alt' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark fas fa-user-plus' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark fas fa-sign-in-alt' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mt-5">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer class="mt-5">
      <div class="bg_test">
        <h1 class="text">Better pregnant woman life</h1>
      </div>
    </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">

    <span class="calendar-title"> <%= start_date.year %>年<%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.previous', default: '先月'), calendar.url_for_previous_view %>,
    <%= link_to t('simple_calendar.next', default: '来月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped calendar">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>